### ISSUE TITLE
[Feature Request]: Can you make a version for SaturnCloud.io?

### ISSUE THREAD

**Issue by ghost** [camenduru/stable-diffusion-webui#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Available to run in SaturnCloud notebook

### Proposed workflow

A simple step by step guide to setup and use in SaturnCloud

### Additional information

It'll be helpful if you could, thanks a lot.

**Comment by camenduru** [comment]
![image](https://github.com/camenduru/stable-diffusion-webui/assets/54370274/5fff4b40-196e-4a92-9833-0cdd098daeb0)

SaturnCloud VMs' disks are just 2Gi 😭 we can't use stable-diffusion-webui

**Comment by ghost** [comment]
There's an 'Show Advance Options' that gives you 10gb. Go to edit, it'll show (Had that in the first time also). Thank you for making this version.

![Screenshot 2023-08-08 052641](https://github.com/camenduru/stable-diffusion-webui/assets/52849704/b150b98c-ac10-4d71-97a6-fa7ae765e323)

**Comment by camenduru** [comment]
thanks ❤ https://github.com/camenduru/stable-diffusion-webui-saturncloud

**Comment by ghost** [comment]
Thank you!
