### ISSUE TITLE
Found someone who manage to bypass colab warning and it actually works

### ISSUE THREAD

**Issue by ghost** [camenduru/stable-diffusion-webui#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Using this person stable diffusion somehow bypass the colab warning and actually manage to work without disconnecting.

https://www.youtube.com/watch?v=P0kEULXl92w&ab_channel=marat_ai

Perhaps you could make your own version using his.

### Proposed workflow

Using marat_ai colab version of stable diffusion to make your own version.

### Additional information

Not sure how he done it, but it works.

**Comment by camenduru** [comment]
thanks ❤
