### ISSUE TITLE
[Bug]: I can't see Haku's Extension in this Web UI of Stable Diffusion

### ISSUE THREAD

**Issue by Karakor23** [camenduru/stable-diffusion-webui#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

[Bug]: I can't see Haku's Extension in this Web UI of Stable Diffusion

### Steps to reproduce the problem

1. Go to .Extensions.. 
2. Press ..Haku Extension.
3. .Restart
4. nothing there.

### What should have happened?

[Bug]: I can't see Haku's Extension in this Web UI of Stable Diffusion

### Commit where the problem happens

[Bug]: I can't see Haku's Extension in this Web UI of Stable Diffusion

### What platforms do you use to access the UI ?

Windows, MacOS

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
[Bug]: I can't see Haku's Extension in this Web UI of Stable Diffusion
```

### List of extensions

[Bug]: I can't see Haku's Extension in this Web UI of Stable Diffusion

### Console logs

```Shell
[Bug]: I can't see Haku's Extension in this Web UI of Stable Diffusion
```

### Additional information

[Bug]: I can't see Haku's Extension in this Web UI of Stable Diffusion

**Comment by camenduru** [comment]
@Karakor23 please open the issue here https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues
