### ISSUE TITLE
[Bug]: Download issue in Civitai plugin for single version model

### ISSUE THREAD

**Issue by kutekrish** [camenduru/stable-diffusion-webui#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

In the sd-civitai-browser plugin, when you use Civitai tab to search for any model or LoRA or textual inversion and choose the model from the drop-down, if it has only one version, though the version is pre selected in the UI, the model download URL and other details are not loaded. Due to this, you cannot download from Civitai unless the model has atleast 2 versions so you could choose one from the drop-down.

Suggestion is to keep an empty selection, just like how the model drop-down behaves when you do a search by search term and click the load button. 

### Steps to reproduce the problem

1. Go to Civitai tab
2. Check the check box to enable search 
3. Choose LoRA
4. Search for `Musume`
5. Choose `T.M. Opera O from Uma Musume - LORA` from first drop-down
6. Since this has only one version, though selected automatically, you'll not be able to download it
7. Now, choose `Wonder Acute from Uma Musume` and since this has 3 versions, you can choose and then download 

### What should have happened?

Suggestion is to keep an empty selection, just like how the model drop-down behaves when you do a search by search term and click the load button. 

### Commit where the problem happens

Lstest

### What platforms do you use to access the UI ?

Other/Cloud

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--share --xformers --enable-insecure-extension-access
```

### List of extensions

Civitai

### Console logs

```Shell
NA
```

**Comment by camenduru** [comment]
thanks for the issue I think we fixed this
