### ISSUE TITLE
Pull from master to fix fastapi bug for v2

### ISSUE THREAD

**Issue by etherealxx** [camenduru/stable-diffusion-webui#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

but you need to edit all the colab since master use fastapi==0.90.1 whereas yours is fastapi==0.90.0

### Proposed workflow

.

### Additional information

.

**Comment by camenduru** [comment]
thanks @etherealxx ❤
